name: Set up dependencies
description: Set up Node.js and install package dependencies.

# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
inputs:
  path-to-dependency-cache:
    description: "Path to the dependency cache"
    # Defaults to any lock yarn lock file in any subfolder (e.g. includes ./frontend/yarn.lock)
    default: "**/package-lock.json"
  working-directory-path:
    description: "Path to working directory"
    default: "./"

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: ${{ inputs.path-to-dependency-cache }}
        node-version-file: ${{ inputs.working-directory-path }}/.nvmrc

    - name: Install dependencies
      run: npm ci --no-audit --prefer-offline
      shell: bash
      working-directory: ${{ inputs.working-directory-path }}
